#JSON TREE runtime settings
#Sat Aug 01 23:24:20 CEST 2026
defaultCurlUserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36
largePreviewThresholdBytes=2048576
nightModeEnabled=false
prettyOnLargePreviewEnabled=false
viewerChunkBytes=153600
